---
title: C6320 | Microsoft-Dokumentation
ms.date: 11/15/2016
ms.prod: visual-studio-dev14
ms.technology: vs-ide-code-analysis
ms.topic: reference
f1_keywords:
- C6320
helpviewer_keywords:
- C6320
ms.assetid: fb9e568e-b3d4-4ce2-a276-a64ad74d7b1e
caps.latest.revision: 12
author: mikeblome
ms.author: mblome
manager: jillfra
ms.openlocfilehash: 466c2cfda439a31950bfb384d941287eb2e807f3
ms.sourcegitcommit: 08fc78516f1107b83f46e2401888df4868bb1e40
ms.translationtype: MT
ms.contentlocale: de-DE
ms.lasthandoff: 05/15/2019
ms.locfileid: "65685797"
---
# <a name="c6320"></a>C6320
[!INCLUDE[vs2017banner](../includes/vs2017banner.md)]

Warnung C6320: Der Ausnahmefilterausdruck ist die EXCEPTION_EXECUTE_HANDLER-Konstante. Hierdurch werden möglicherweise Ausnahmen maskiert, für die keine Behandlung vorgesehen war.  
  
 Diese Warnung gibt an, den Nebeneffekt, dass der Verwendung von EXCEPTION_EXECUTE_HANDLER-Konstante in __except Block. In diesem Fall die Anweisung in der \__except-Block wird immer ausgeführt, um die Ausnahme, einschließlich Ausnahmen, die Sie nicht in einer bestimmten Funktion behandeln möchten. Es wird empfohlen, dass Sie die Ausnahme vor der Behandlung zu überprüfen.  
  
## <a name="example"></a>Beispiel  
 Der folgende Code generiert diese Warnung, weil der __except-block versuchen, die Ausnahmen aller Art zu behandeln:  
  
```  
#include <stdio.h>   
#include <excpt.h>   
  
void f(int *p)   
{   
   __try  
   {   
      puts("in try");   
      *p = 13;  // might cause access violation exception  
      // code ...  
   }   
   __except(EXCEPTION_EXECUTE_HANDLER) // warning  
   {   
      puts("in except");   
      // code ...  
   }   
}   
```  
  
 Verwenden Sie zum Beheben dieser Warnung `GetExceptionCode` zu prüfen, eine bestimmte Ausnahme vor der Behandlung wie im folgenden Code gezeigt:  
  
```  
#include <stdio.h>   
#include <windows.h>   
#include <excpt.h>   
  
void f(int *p)   
{   
   __try  
   {   
      puts("in try");   
      *p = 13;    // might cause access violation exception   
      // code ...  
   }   
   __except(GetExceptionCode()==EXCEPTION_ACCESS_VIOLATION ?   
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)  
   {   
      puts("in except");   
      // code ...  
   }   
}  
```  
  
## <a name="see-also"></a>Siehe auch  
 [try-except-Anweisung](https://msdn.microsoft.com/library/30d60071-ea49-4bfb-a8e6-7a420de66381)
