---
title: C28125
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C28125
helpviewer_keywords:
- C28125
ms.assetid: 3f7b8db4-6a64-4480-919e-3f3ceca7f948
author: mikeblome
ms.author: mblome
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: e66e6c3eb98fdb51c6d47c70a29240ed96a8fa04
ms.sourcegitcommit: 174c992ecdc868ecbf7d3cee654bbc2855aeb67d
ms.translationtype: MT
ms.contentlocale: de-DE
ms.lasthandoff: 12/06/2019
ms.locfileid: "74879138"
---
# <a name="c28125"></a>C28125
Warnung C28125: Die Funktion muss innerhalb eines try/except-Blocks aufgerufen werden.

 Der Treiber ruft eine Funktion auf, die innerhalb eines try/with-Blocks aufgerufen werden muss, z. b. [Probe forread](/windows-hardware/drivers/ddi/content/wdm/nf-wdm-probeforread), [probeforwrite](/windows-hardware/drivers/ddi/content/wdm/nf-wdm-probeforwrite), [MmProbeAndLockPages](/windows-hardware/drivers/ddi/content/wdm/nf-wdm-mmprobeandlockpages).

## <a name="example"></a>Beispiel
 Im folgenden Codebeispiel wird diese Warnung generiert:

```cpp
ProbeForRead(addr, len, 4);
```

 Im folgenden Codebeispiel wird diese Warnung vermieden:

```cpp
__try
{
    ProbeForRead(addr, len, 4);
}
__except(EXCEPTION_EXECUTE_HANDLER)
{
    Status = GetExceptionCode();
    ... report error status
}
```
