---
title: C28105
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C28105
helpviewer_keywords:
- C28105
ms.assetid: 5afdec78-30eb-470c-980f-93d0cb3e74cc
author: mikeblome
ms.author: mblome
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: bcd98a6e49b980719b458ebbb79090b0a3bfb587
ms.sourcegitcommit: 535ef05b1e553f0fc66082cd2e0998817eb2a56a
ms.translationtype: MT
ms.contentlocale: de-DE
ms.lasthandoff: 10/07/2019
ms.locfileid: "72010654"
---
# <a name="c28105"></a>C28105
Warnung C28105: Verlust von Ressource aufgrund einer Ausnahme

 Die angegebene Ressource wird nicht freigegeben, wenn eine Ausnahme ausgelöst wird. Die vom Pfad angegebene Anweisung kann eine Ausnahme auslöst. Diese Warnung ähnelt der Warnung [C28103](../code-quality/c28103.md), mit dem Unterschied, dass in diesem Fall eine Ausnahme beteiligt ist.

## <a name="example"></a>Beispiel
 Im folgenden Codebeispiel wird diese Warnung generiert:

```
res = KeSaveFloatingPointState(buffer);

res = AllocateResource(Resource);
char *p2 = new char[10]; // could throw

delete[] p2;
FreeResource(Resource)
```

 Im folgenden Codebeispiel wird diese Warnung vermieden:

```
res = AllocateResource(Resource);
char *p2;

try {
    p2 = new char[10];
} catch (std::bad_alloc *e) {
    // just handle the throw
    ;
}
FreeResource(Resource)
```