---
title: C28125
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C28125
helpviewer_keywords:
- C28125
ms.assetid: 3f7b8db4-6a64-4480-919e-3f3ceca7f948
author: mikeblome
ms.author: mblome
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: c5811f3174db710985e8fe074fa2785e458d358a
ms.sourcegitcommit: 8589d85cc10710ef87e6363a2effa5ee5610d46a
ms.translationtype: MT
ms.contentlocale: de-DE
ms.lasthandoff: 10/23/2019
ms.locfileid: "72806738"
---
# <a name="c28125"></a>C28125
Warnung C28125: Die Funktion muss innerhalb eines try/except-Blocks aufgerufen werden.

 Der Treiber ruft eine Funktion auf, die innerhalb eines try/with-Blocks aufgerufen werden muss, z. b. [Probe forread](/windows-hardware/drivers/ddi/content/wdm/nf-wdm-probeforread), [probeforwrite](/windows-hardware/drivers/ddi/content/wdm/nf-wdm-probeforwrite), [MmProbeAndLockPages](/windows-hardware/drivers/ddi/content/wdm/nf-wdm-mmprobeandlockpages).

## <a name="example"></a>Beispiel
 Im folgenden Codebeispiel wird diese Warnung generiert:

```
ProbeForRead(addr, len, 4);
```

 Im folgenden Codebeispiel wird diese Warnung vermieden:

```

__try
{
    ProbeForRead(addr, len, 4);
}
__except(EXCEPTION_EXECUTE_HANDLER)
{
    Status = GetExceptionCode();
    ... report error status
}
```
