---
title: C6318
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C6318
helpviewer_keywords:
- C6318
ms.assetid: 3284a83e-bb8e-461c-adcc-cfc66ceea05e
author: mikeblome
ms.author: mblome
manager: wpickett
ms.workload:
- multiple
ms.openlocfilehash: f472860cd338dee15b4005db16ba09de1e314071
ms.sourcegitcommit: 94b3a052fb1229c7e7f8804b09c1d403385c7630
ms.translationtype: MT
ms.contentlocale: de-DE
ms.lasthandoff: 04/23/2019
ms.locfileid: "62781894"
---
# <a name="c6318"></a>C6318
Warnung C6318: Falsch definiertes __try /\__except: Verwendung der EXCEPTION_CONTINUE_SEARCH Konstanten oder einer anderen Konstanten, die in der Ausnahmefilterausdruck null ergibt. Der Code im Ausnahmehandlerblock wird nicht ausgeführt.

 Diese Warnung gibt an, dass wenn der geschützte Block dieser strukturierte Ausnahmehandler eine Ausnahme auftritt, die Ausnahme nicht da behandelt, wird der Konstante `EXCECPTION_CONTINUE_SEARCH` wird in der Ausnahmefilterausdruck verwendet.

 Dieser Code ist äquivalent zu den geschützten Block ohne Ausnahmehandlerblock, da der Handlerblock nicht ausgeführt wird.

## <a name="example"></a>Beispiel
 Der folgende Code generiert diese Warnung:

```
#include <excpt.h>
#include <stdio.h>

void f (char *pch)
{
  __try
  {
    // assignment might fail
    *pch = 0;
  }
  __except (EXCEPTION_CONTINUE_SEARCH) // warning 6318
  {
    puts("Exception Occurred");
  }
}
```

 So korrigieren Sie die Warnung unter Verwendung des folgenden Codes

```
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *pch)
{
  __try
  {
    // assignment might fail
    *pch = 0;
  }
  __except( (GetExceptionCode() == EXCEPTION_ACCESS_VIOLATION) ?
                EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH )
  {
    puts("Access violation");
  }
}
```

## <a name="see-also"></a>Siehe auch
 [try-except-Anweisung](/cpp/cpp/try-except-statement)