---
title: C6318
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C6318
helpviewer_keywords:
- C6318
ms.assetid: 3284a83e-bb8e-461c-adcc-cfc66ceea05e
author: mikeblome
ms.author: mblome
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: 1feeb41725f02985aa35f94815578c5c216ba90f
ms.sourcegitcommit: 535ef05b1e553f0fc66082cd2e0998817eb2a56a
ms.translationtype: MT
ms.contentlocale: de-DE
ms.lasthandoff: 10/07/2019
ms.locfileid: "72013008"
---
# <a name="c6318"></a>C6318
Warnung C6318: Falsch definierte __try/@no__t -0 _except: Verwendung der Konstanten EXCEPTION_CONTINUE_SEARCH oder einer anderen Konstante, die im Ausnahme Filter Ausdruck NULL ergibt. Der Code im Ausnahmehandlerblock wird nicht ausgef端hrt.

 Diese Warnung gibt an, dass die Ausnahme nicht behandelt wird, wenn eine Ausnahme im gesch端tzten Block dieses strukturierten Ausnahme Handlers auftritt, da die Konstante `EXCECPTION_CONTINUE_SEARCH` im Ausnahme Filter Ausdruck verwendet wird.

 Dieser Code entspricht dem gesch端tzten Block ohne den Ausnahmehandlerblock, da der Handlerblock nicht ausgef端hrt wird.

## <a name="example"></a>Beispiel
 Der folgende Code generiert diese Warnung:

```
#include <excpt.h>
#include <stdio.h>

void f (char *pch)
{
  __try
  {
    // assignment might fail
    *pch = 0;
  }
  __except (EXCEPTION_CONTINUE_SEARCH) // warning 6318
  {
    puts("Exception Occurred");
  }
}
```

 So korrigieren Sie die Warnung unter Verwendung des folgenden Codes

```
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *pch)
{
  __try
  {
    // assignment might fail
    *pch = 0;
  }
  __except( (GetExceptionCode() == EXCEPTION_ACCESS_VIOLATION) ?
                EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH )
  {
    puts("Access violation");
  }
}
```

## <a name="see-also"></a>Siehe auch
 [try-except-Anweisung](/cpp/cpp/try-except-statement)